export const COUNTRIES = [
  { code: '+55',   flag: '🇧🇷', name: 'Brasil',              mask: '(##) # ####-####', minDigits: 11, maxDigits: 11 },
  { code: '+1',    flag: '🇺🇸', name: 'EUA / Canadá',        mask: '(###) ###-####',   minDigits: 10, maxDigits: 10 },
  { code: '+44',   flag: '🇬🇧', name: 'Reino Unido',         mask: '#### ### ####',    minDigits: 10, maxDigits: 11 },
  { code: '+49',   flag: '🇩🇪', name: 'Alemanha',            mask: '#### ########',    minDigits: 10, maxDigits: 12 },
  { code: '+33',   flag: '🇫🇷', name: 'França',              mask: '## ## ## ## ##',   minDigits: 9,  maxDigits: 10 },
  { code: '+34',   flag: '🇪🇸', name: 'Espanha',             mask: '### ### ###',      minDigits: 9,  maxDigits: 9  },
  { code: '+39',   flag: '🇮🇹', name: 'Itália',              mask: '### ### ####',     minDigits: 9,  maxDigits: 11 },
  { code: '+351',  flag: '🇵🇹', name: 'Portugal',            mask: '### ### ###',      minDigits: 9,  maxDigits: 9  },
  { code: '+54',   flag: '🇦🇷', name: 'Argentina',           mask: '(###) ###-####',   minDigits: 10, maxDigits: 10 },
  { code: '+56',   flag: '🇨🇱', name: 'Chile',               mask: '# #### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+57',   flag: '🇨🇴', name: 'Colômbia',            mask: '### ### ####',     minDigits: 10, maxDigits: 10 },
  { code: '+51',   flag: '🇵🇪', name: 'Peru',                mask: '### ### ###',      minDigits: 9,  maxDigits: 9  },
  { code: '+58',   flag: '🇻🇪', name: 'Venezuela',           mask: '(###) ###-####',   minDigits: 10, maxDigits: 10 },
  { code: '+591',  flag: '🇧🇴', name: 'Bolívia',             mask: '########',         minDigits: 8,  maxDigits: 8  },
  { code: '+595',  flag: '🇵🇾', name: 'Paraguai',            mask: '### ######',       minDigits: 9,  maxDigits: 9  },
  { code: '+598',  flag: '🇺🇾', name: 'Uruguai',             mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+593',  flag: '🇪🇨', name: 'Equador',             mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+52',   flag: '🇲🇽', name: 'México',              mask: '## #### ####',     minDigits: 10, maxDigits: 10 },
  { code: '+506',  flag: '🇨🇷', name: 'Costa Rica',          mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+507',  flag: '🇵🇦', name: 'Panamá',              mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+503',  flag: '🇸🇻', name: 'El Salvador',         mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+502',  flag: '🇬🇹', name: 'Guatemala',           mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+504',  flag: '🇭🇳', name: 'Honduras',            mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+505',  flag: '🇳🇮', name: 'Nicarágua',           mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+1787', flag: '🇵🇷', name: 'Porto Rico',          mask: '### ####',         minDigits: 7,  maxDigits: 7  },
  { code: '+53',   flag: '🇨🇺', name: 'Cuba',                mask: '# ### ####',       minDigits: 8,  maxDigits: 8  },
  { code: '+509',  flag: '🇭🇹', name: 'Haiti',               mask: '## ## ####',       minDigits: 8,  maxDigits: 8  },
  { code: '+1809', flag: '🇩🇴', name: 'Rep. Dominicana',     mask: '### ####',         minDigits: 7,  maxDigits: 7  },
  { code: '+7',    flag: '🇷🇺', name: 'Rússia',              mask: '(###) ###-##-##',  minDigits: 10, maxDigits: 10 },
  { code: '+380',  flag: '🇺🇦', name: 'Ucrânia',             mask: '## ### ## ##',     minDigits: 9,  maxDigits: 9  },
  { code: '+48',   flag: '🇵🇱', name: 'Polônia',             mask: '### ### ###',      minDigits: 9,  maxDigits: 9  },
  { code: '+31',   flag: '🇳🇱', name: 'Holanda',             mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+32',   flag: '🇧🇪', name: 'Bélgica',             mask: '### ## ## ##',     minDigits: 9,  maxDigits: 9  },
  { code: '+41',   flag: '🇨🇭', name: 'Suíça',               mask: '## ### ## ##',     minDigits: 9,  maxDigits: 9  },
  { code: '+43',   flag: '🇦🇹', name: 'Áustria',             mask: '### ######',       minDigits: 7,  maxDigits: 13 },
  { code: '+46',   flag: '🇸🇪', name: 'Suécia',              mask: '##-### ## ##',     minDigits: 9,  maxDigits: 9  },
  { code: '+47',   flag: '🇳🇴', name: 'Noruega',             mask: '### ## ###',       minDigits: 8,  maxDigits: 8  },
  { code: '+45',   flag: '🇩🇰', name: 'Dinamarca',           mask: '## ## ## ##',      minDigits: 8,  maxDigits: 8  },
  { code: '+358',  flag: '🇫🇮', name: 'Finlândia',           mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+353',  flag: '🇮🇪', name: 'Irlanda',             mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+30',   flag: '🇬🇷', name: 'Grécia',              mask: '### ### ####',     minDigits: 10, maxDigits: 10 },
  { code: '+420',  flag: '🇨🇿', name: 'República Tcheca',    mask: '### ### ###',      minDigits: 9,  maxDigits: 9  },
  { code: '+36',   flag: '🇭🇺', name: 'Hungria',             mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+40',   flag: '🇷🇴', name: 'Romênia',             mask: '### ### ###',      minDigits: 9,  maxDigits: 9  },
  { code: '+359',  flag: '🇧🇬', name: 'Bulgária',            mask: '### ### ###',      minDigits: 9,  maxDigits: 9  },
  { code: '+385',  flag: '🇭🇷', name: 'Croácia',             mask: '## ### ####',      minDigits: 8,  maxDigits: 9  },
  { code: '+381',  flag: '🇷🇸', name: 'Sérvia',              mask: '## ### ####',      minDigits: 8,  maxDigits: 9  },
  { code: '+90',   flag: '🇹🇷', name: 'Turquia',             mask: '(###) ### ####',   minDigits: 10, maxDigits: 10 },
  { code: '+972',  flag: '🇮🇱', name: 'Israel',              mask: '##-### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+966',  flag: '🇸🇦', name: 'Arábia Saudita',      mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+971',  flag: '🇦🇪', name: 'Emirados Árabes',     mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+965',  flag: '🇰🇼', name: 'Kuwait',              mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+974',  flag: '🇶🇦', name: 'Qatar',               mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+20',   flag: '🇪🇬', name: 'Egito',               mask: '### ### ####',     minDigits: 10, maxDigits: 10 },
  { code: '+27',   flag: '🇿🇦', name: 'África do Sul',       mask: '## ### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+234',  flag: '🇳🇬', name: 'Nigéria',             mask: '### ### ####',     minDigits: 10, maxDigits: 10 },
  { code: '+254',  flag: '🇰🇪', name: 'Quênia',              mask: '### ######',       minDigits: 9,  maxDigits: 9  },
  { code: '+212',  flag: '🇲🇦', name: 'Marrocos',            mask: '##-######',        minDigits: 9,  maxDigits: 9  },
  { code: '+213',  flag: '🇩🇿', name: 'Argélia',             mask: '### ## ## ##',     minDigits: 9,  maxDigits: 9  },
  { code: '+216',  flag: '🇹🇳', name: 'Tunísia',             mask: '## ### ###',       minDigits: 8,  maxDigits: 8  },
  { code: '+91',   flag: '🇮🇳', name: 'Índia',               mask: '##### #####',      minDigits: 10, maxDigits: 10 },
  { code: '+86',   flag: '🇨🇳', name: 'China',               mask: '### #### ####',    minDigits: 11, maxDigits: 11 },
  { code: '+81',   flag: '🇯🇵', name: 'Japão',               mask: '##-####-####',     minDigits: 10, maxDigits: 10 },
  { code: '+82',   flag: '🇰🇷', name: 'Coreia do Sul',       mask: '##-####-####',     minDigits: 9,  maxDigits: 10 },
  { code: '+60',   flag: '🇲🇾', name: 'Malásia',             mask: '##-#### ####',     minDigits: 9,  maxDigits: 10 },
  { code: '+65',   flag: '🇸🇬', name: 'Singapura',           mask: '#### ####',        minDigits: 8,  maxDigits: 8  },
  { code: '+66',   flag: '🇹🇭', name: 'Tailândia',           mask: '##-### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+84',   flag: '🇻🇳', name: 'Vietnã',              mask: '### ### ####',     minDigits: 9,  maxDigits: 10 },
  { code: '+62',   flag: '🇮🇩', name: 'Indonésia',           mask: '####-####-####',   minDigits: 9,  maxDigits: 12 },
  { code: '+63',   flag: '🇵🇭', name: 'Filipinas',           mask: '#### ### ####',    minDigits: 10, maxDigits: 10 },
  { code: '+61',   flag: '🇦🇺', name: 'Austrália',           mask: '#### ### ###',     minDigits: 9,  maxDigits: 9  },
  { code: '+64',   flag: '🇳🇿', name: 'Nova Zelândia',       mask: '## ### ####',      minDigits: 8,  maxDigits: 9  },
  { code: '+880',  flag: '🇧🇩', name: 'Bangladesh',          mask: '####-######',      minDigits: 10, maxDigits: 10 },
  { code: '+92',   flag: '🇵🇰', name: 'Paquistão',           mask: '###-#######',      minDigits: 10, maxDigits: 10 },
  { code: '+94',   flag: '🇱🇰', name: 'Sri Lanka',           mask: '##-### ####',      minDigits: 9,  maxDigits: 9  },
  { code: '+98',   flag: '🇮🇷', name: 'Irã',                 mask: '###-### ####',     minDigits: 10, maxDigits: 10 },
  { code: '+964',  flag: '🇮🇶', name: 'Iraque',              mask: '### ### ####',     minDigits: 10, maxDigits: 10 },
];